import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import * as React from "react";
import { MagnifyingGlassIcon } from "@radix-ui/react-icons";

//Importerer navbar componentene
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu";

//Importerer søkeboks componentene
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
  CommandShortcut,
} from "@/components/ui/command";

//Importerer alert box for å åpne søkefelt
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";

//Importerer theme provider for å bytte tema
import { ThemeProvider } from "@/components/ui/themeProvider";
import { ThemeToggle } from "@/components/ui/theme-toggle";

//Navbar innhold array
const components: { title: string; href: string; description: string }[] = [
  {
    title: "Valgprosjekt",
    href: "/docs/primitives/alert-dialog",
    description:
      "Nettside som bruker Facebook Autentifikasjon for å lagre valgresultater i en database.",
  },
  {
    title: "Minispill",
    href: "/docs/primitives/hover-card",
    description:
      "Diverse enkle minispill jeg har laget i løpet av skoleårene mine på Glemmen",
  },
  {
    title: "Spill Anmeldelse Side",
    href: "/docs/primitives/progress",
    description:
      "En nettside hvor man kan søke opp spill og se anmelderser og opsummering av spillet",
  },
];

//Font
const inter = Inter({ subsets: ["latin"] });

//Metadata for seo
export const metadata: Metadata = {
  title: "Benjamin Pedersen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className=" " lang="en">
      <body
        className={cn(
          " min-h-screen bg-background text-foreground font-sans antialiased",
          inter.className
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* Navbar */}
          <div className="p-5 flex">
            <NavigationMenu>
              <NavigationMenuList>
                {/* Hjemmeside dropdown nav */}
                <NavigationMenuItem>
                  <NavigationMenuTrigger>Hjemmeside</NavigationMenuTrigger>
                  <NavigationMenuContent>
                    <ul className="grid gap-3 p-4 md:w-[400px] lg:w-[500px] lg:grid-cols-[.75fr_1fr]">
                      <li className="row-span-3">
                        <NavigationMenuLink asChild>
                          <a
                            className="flex h-full w-full select-none flex-col justify-end rounded-md bg-gradient-to-b from-muted/50 to-muted p-6 no-underline outline-none focus:shadow-md"
                            href="/"
                          >
                            <div className="mb-2 mt-4 text-lg font-medium">
                              Benjamin Pedersen
                            </div>
                            <p className="text-sm leading-tight text-muted-foreground">
                              Jeg går på Informasjonsteknologi linjen på Glemmen
                              Vidregående Skole og er intressert i utvikling av
                              nettsider og programmer.
                            </p>
                          </a>
                        </NavigationMenuLink>
                      </li>
                      <ListItem href="/docs" title="Ferdigheter">
                        Informasjon om min IT kompetanse
                      </ListItem>
                      <ListItem href="/docs/installation" title="Utdanning">
                        Informasjon om min Utdanning
                      </ListItem>
                      <ListItem
                        href="/docs/primitives/typography"
                        title="Arbeidserfaring"
                      >
                        Informasjon om Arbeidserfaringen jeg har
                      </ListItem>
                    </ul>
                  </NavigationMenuContent>
                </NavigationMenuItem>

                {/* Prosjekter dropdown nav */}
                <NavigationMenuItem>
                  <NavigationMenuTrigger>Prosjekter</NavigationMenuTrigger>
                  <NavigationMenuContent>
                    <ul className="grid w-[400px] gap-3 p-4 md:w-[500px] md:grid-cols-2 lg:w-[600px] ">
                      {components.map((component) => (
                        <ListItem
                          key={component.title}
                          title={component.title}
                          href={component.href}
                        >
                          {component.description}
                        </ListItem>
                      ))}
                    </ul>
                  </NavigationMenuContent>
                </NavigationMenuItem>

                {/* Søke knapp og søkeboks */}
                <NavigationMenuItem>
                  <AlertDialog>
                    <AlertDialogTrigger className="focus:outline-none focus:ring-0">
                      Søk
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                      <AlertDialogHeader>
                        <Command className="rounded-lg border border-muted shadow-md">
                          <CommandInput placeholder="Type a command or search..." />
                          <CommandList>
                            <CommandEmpty>Ingen resultater.</CommandEmpty>
                            <CommandGroup heading="Hjemmeside">
                              <CommandItem>
                                <span>Ferdigheter</span>
                              </CommandItem>
                              <CommandItem>
                                <span>Utdanning</span>
                              </CommandItem>
                              <CommandItem>
                                <span>Arbeidserfaring</span>
                              </CommandItem>
                            </CommandGroup>
                            <CommandSeparator />
                            <CommandGroup heading="Prosjekter">
                              <CommandItem>
                                <span>Valgprosjekt</span>
                              </CommandItem>
                              <CommandItem>
                                <span>Minispill</span>
                              </CommandItem>
                              <CommandItem>
                                <span>Spill Anmeldelse Side</span>
                              </CommandItem>
                            </CommandGroup>
                          </CommandList>
                        </Command>
                      </AlertDialogHeader>
                    </AlertDialogContent>
                  </AlertDialog>
                </NavigationMenuItem>

                {/* Tema toggler */}
                <div className="flex-1 text-right">
                  <NavigationMenuItem>
                    <ThemeToggle />
                  </NavigationMenuItem>
                </div>
              </NavigationMenuList>
            </NavigationMenu>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

//ListItem component for navbar linker
const ListItem = React.forwardRef<
  React.ElementRef<"a">,
  React.ComponentPropsWithoutRef<"a">
>(({ className, title, children, ...props }, ref) => {
  return (
    <li>
      <NavigationMenuLink asChild>
        <a
          ref={ref}
          className={cn(
            "block select-none space-y-1 rounded-md p-3 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground",
            className
          )}
          {...props}
        >
          <div className="text-sm font-medium leading-none">{title}</div>
          <p className="line-clamp-2 text-sm leading-snug text-muted-foreground">
            {children}
          </p>
        </a>
      </NavigationMenuLink>
    </li>
  );
});
ListItem.displayName = "ListItem";
